Django/LEARN/Django/Course/Django-Tutorial/02-Django-and-Templates/my_site/my_app/urls.py
from . import views
from django.urls import path, include

# register the app namespace
# URL names
app_name = 'my_app'

urlpatterns = [
    path('', views.exmaple_view, name='example'),
    path('variable/', views.variable_view, name='variable')
]

Django/LEARN/Django/Course/Django-Tutorial/02-Django-and-Templates/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path('my_app/', include('my_app.urls')),
]

# refer
handler404 = 'my_site.views.custom_page_not_found_view'

Django/LEARN/Django/Course/Django-Tutorial/02-Django-and-Templates/my_site/my_app/views.py
from django.shortcuts import render

# Create your views here.


def exmaple_view(request):
    # refer to templates floder: my_app/templates/my_app/example.html
    return render(request, 'my_app/example.html')


def variable_view(request):
    my_var = {"first_name": 'rosaLind', 'last_name': 'franklin', 'some_list': [1, 2, 3], 'some_dict': {'inside_key': 'inside_value'},
              'user_logged_in': True}
    # recive request and send to template with context
    return render(request, 'my_app/variable.html', context=my_var)

Django/LEARN/Django/Course/Django-Tutorial/02-Django-and-Templates/my_site/my_site/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, 'layouts.html')


def custom_page_not_found_view(request, exception):
    return render(request, '404.html', status=404)

Django/LEARN/Django/Course/Django-Tutorial/02-Django-and-Templates/my_site/my_app/templates/my_app/example.html
{% extends 'layouts.html' %} {% block content %} {% load static %}
<div class="container">
	<h1>EXAMPLE HTML TEMPLATE</h1>
	<h1><a href="{% url 'my_app:variable' %}">CLICK ME TO GO TO VARIABLE</a></h1>
	<img src="{% static 'my_app/django.png' %}" alt="my image" />
</div>
{% endblock content %}

Django/LEARN/Django/Course/Django-Tutorial/02-Django-and-Templates/my_site/my_app/templates/my_app/variable.html
{% extends 'layouts.html' %} {% block content %}
<div class="container">
	<div class="jumbotron">
		<h1>VARIABLE.HTML</h1>
		<!-- use '|' to call filter of Django template language  -->
		<h2>Her first name was {{first_name | upper}} and her last name was {{last_name}}</h2>
		<h2>Her first name was {{first_name | lower | capfirst}} and her last name was {{last_name |capfirst}}</h2>
		<h2>Her first name was {{first_name | length}} and her last name was {{last_name}}</h2>
		<!-- Django template language use '.x' as index -->
		<h2>{{some_list.0}}</h2>
		<h2>{{some_dict.inside_key}}</h2>
		<!-- Django template language comment -->
		<!-- <h2>{# This is an Django template language comment #}</h2> -->
		<!-- Loop -->
		<ul>
			{% for item in some_list %}
			<li>{{ item }}</li>
			<!-- default value in case list is empty -->
			{% empty %}
			<p>no data </p>
			{% endfor %}
		</ul>
		<!-- loop for dict-->
		<ul>
			{% for k,v in some_dict.items %}
			<li>{{ k }},{{ v }}</li>

			{% endfor %}
		</ul>

		<!--IF ELSE-->

		{% if user_logged_in %}
		<h1>User is logged In !</h1>
		{% else %}
		<h1>No one is logged In</h1>
		{% endif %}
		<ul>
			{% for num in some_list %} {% if num == 2 %}
			<li>TWO</li>
			{% else %}
			<li>{{ num }}</li>
			{% endif %} {% endfor %}
		</ul>

		{% if user_logged_in %}
		<h1>Welcome back {{ first_name }}</h1>
		{% endif %}
	</div>
</div>
{% endblock content %}